#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/rocm-core \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w" \
    -DVERSION_MAJOR="$ROCM_MAJOR_VERSION" \
    -DVERSION_MINOR="$ROCM_MINOR_VERSION" \
    -DVERSION_PATCH="$ROCM_PATCH_VERSION" \
    -DROCM_VERSION="$ROCM_VERSION" \
    -DBUILD_ID=0 \
    -G Ninja \
    $ROCM_SOURCE_DIR/rocm-core

cmake --build $ROCM_BUILD_DIR/rocm-core
cmake --install $ROCM_BUILD_DIR/rocm-core --prefix $ROCM_INSTALL_DIR
