#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/rocsparse \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=$ROCM_INSTALL_DIR/lib/llvm/bin/amdclang \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/lib/llvm/bin/amdclang++ \
    -DCMAKE_C_FLAGS="$COMPILER_FLAGS -Wno-error=unused-command-line-argument" \
    -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS -Wno-error=unused-command-line-argument" \
    -DGPU_TARGETS="$AMDGPU_TARGETS" \
    -DBUILD_CLIENTS_TESTS=$ENABLE_BUILD_TESTING \
    -DBUILD_CLIENTS_SAMPLES=OFF \
    -DBUILD_CLIENTS_BENCHMARKS=OFF \
    -G Ninja \
    $ROCM_SOURCE_DIR/rocSPARSE

cmake --build $ROCM_BUILD_DIR/rocsparse
cmake --install $ROCM_BUILD_DIR/rocsparse --prefix $ROCM_INSTALL_DIR
