#! /usr/bin/env bash

set -e

pushd $ROCM_SOURCE_DIR/MIOpen/src > /dev/null

find . -type f -name "*mha*.cpp" | while read -r mha_source;
do
    sed -i "s/MIOPEN_USE_COMPOSABLEKERNEL/MIOPEN_USE_CK_MHA_OPS/g" "$mha_source"
done

find . -type f -name "*xdl*.cpp" | while read -r xdl_source;
do
    sed -i "s/MIOPEN_USE_COMPOSABLEKERNEL/MIOPEN_USE_CK_XDL_OPS/g" "$xdl_source"
done

sed -i "s/MIOPEN_USE_COMPOSABLEKERNEL/MIOPEN_USE_CK_XDL_OPS/g" \
    mlo_dir_conv.cpp \
    solver/conv_ck_igemm_fwd_bias_res_add_activ_fused.cpp \
    solver/conv_ck_igemm_fwd_bias_activ_fused.cpp

popd > /dev/null

cmake \
    -B $ROCM_BUILD_DIR/miopen \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=$ROCM_INSTALL_DIR/lib/llvm/bin/amdclang \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/lib/llvm/bin/amdclang++ \
    -DCMAKE_C_FLAGS="$COMPILER_FLAGS -Wno-error=unused-command-line-argument" \
    -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS -Wno-error=unused-command-line-argument" \
    -DGPU_TARGETS="$AMDGPU_TARGETS" \
    -DBUILD_TESTING=OFF \
    -DMIOPEN_USE_COMPOSABLEKERNEL=ON \
    -DMIOPEN_USE_MLIR=ON \
    -DMIOPEN_USE_HIPBLASLT=OFF \
    -DMIOPEN_BUILD_DRIVER=OFF \
    -G Ninja \
    $ROCM_SOURCE_DIR/MIOpen

cmake --build $ROCM_BUILD_DIR/miopen
cmake --install $ROCM_BUILD_DIR/miopen --prefix $ROCM_INSTALL_DIR
