#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/rocm-smi-lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=$ROCM_INSTALL_DIR/lib/llvm/bin/amdclang \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/lib/llvm/bin/amdclang++ \
    -DCMAKE_C_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DBUILD_TESTS=$ENABLE_BUILD_TESTING \
    -G Ninja \
    $ROCM_SOURCE_DIR/rocm_smi_lib

cmake --build $ROCM_BUILD_DIR/rocm-smi-lib
cmake --install $ROCM_BUILD_DIR/rocm-smi-lib --prefix $ROCM_INSTALL_DIR
