#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/comgr \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=$ROCM_INSTALL_DIR/lib/llvm/bin/amdclang \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/lib/llvm/bin/amdclang++ \
    -DCMAKE_C_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DBUILD_TESTING=$ENABLE_BUILD_TESTING \
    -DROCM_CCACHE_BUILD=ON \
    -G Ninja \
    $ROCM_SOURCE_DIR/llvm-project/amd/comgr

cmake --build $ROCM_BUILD_DIR/comgr
cmake --install $ROCM_BUILD_DIR/comgr --prefix $ROCM_INSTALL_DIR
