#!/bin/bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/hipify \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=$ROCM_INSTALL_DIR/lib/llvm/bin/amdclang \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/lib/llvm/bin/amdclang++ \
    -DCMAKE_C_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DHIPIFY_CLANG_TESTS=OFF \
    -G Ninja \
    $ROCM_SOURCE_DIR/HIPIFY

cmake --build $ROCM_BUILD_DIR/hipify
cmake --install $ROCM_BUILD_DIR/hipify --prefix $ROCM_INSTALL_DIR
chmod +x $ROCM_INSTALL_DIR/bin/hipify-perl
