#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/roctracer \
    -DCMAKE_C_COMPILER=$ROCM_INSTALL_DIR/lib/llvm/bin/amdclang \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/lib/llvm/bin/amdclang++ \
    -DCMAKE_C_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DCMAKE_BUILD_TYPE=Release \
    -DAMDGPU_TARGETS="$AMDGPU_TARGETS" \
    -G Ninja \
    $ROCM_SOURCE_DIR/roctracer

cmake --build $ROCM_BUILD_DIR/roctracer
cmake --install $ROCM_BUILD_DIR/roctracer --prefix $ROCM_INSTALL_DIR
