#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/hipfft \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/lib/llvm/bin/amdclang++ \
    -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS -Wno-error=unused-command-line-argument" \
    -DGPU_TARGETS="$AMDGPU_TARGETS" \
    -DHIP_ROOT_DIR="$ROCM_INSTALL_DIR" \
    -DBUILD_CLIENTS=$ENABLE_BUILD_TESTING \
    -G Ninja \
    $ROCM_SOURCE_DIR/hipFFT

cmake --build $ROCM_BUILD_DIR/hipfft
cmake --install $ROCM_BUILD_DIR/hipfft --prefix $ROCM_INSTALL_DIR
