#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/flame \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_FLAGS="-march=native -O3 -s -w" \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w" \
    -DLIBAOCLUTILS_LIBRARY_PATH=/opt/blis/lib/libaoclutils.so \
    -DLIBAOCLUTILS_INCLUDE_PATH=/opt/blis/include \
    -DCMAKE_INSTALL_PREFIX=/opt/blis \
    -DENABLE_AMD_FLAGS=ON \
    -DERROR_CHECKING_LEVEL=3 \
    -DBUILD_TEST=OFF \
    -G Ninja \
    $ROCM_WORKING_DIR/flame 

cmake --build $ROCM_BUILD_DIR/flame
cmake --install $ROCM_BUILD_DIR/flame 
