#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/blis \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_FLAGS="-march=native -O3 -s -w" \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w" \
    -DCMAKE_INSTALL_PREFIX=/opt/blis \
    -DBLIS_CONFIG_FAMILY=auto \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_STATIC_LIBS=OFF \
    -G Ninja \
    $ROCM_WORKING_DIR/blis 

cmake --build $ROCM_BUILD_DIR/blis
cmake --install $ROCM_BUILD_DIR/blis
