#! /usr/bin/env bash

## Not buildable with GCC >= 15 at the moment.
# We will switch to Clang until AMD or GCC devs fix it.
# https://github.com/amd/blis/issues/34

pacman -S --noconfirm --needed clang

set -e

cmake \
    -B $ROCM_BUILD_DIR/blis \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=/usr/bin/clang \
    -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
    -DCMAKE_C_FLAGS="$COMPILER_FLAGS" \
    -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS" \
    -DCMAKE_INSTALL_PREFIX=/opt/blis \
    -DBLIS_CONFIG_FAMILY=auto \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_STATIC_LIBS=OFF \
    -G Ninja \
    $ROCM_WORKING_DIR/blis 

cmake --build $ROCM_BUILD_DIR/blis
cmake --install $ROCM_BUILD_DIR/blis

pacman -Rs --noconfirm clang
