#! /usr/bin/env bash

## PyTorch can't be built due to a GCC bug introduced in version 12, so we need to apply the following workarounds:
# export CMAKE_C_FLAGS=-Wno-error=maybe-uninitialized -Wno-error=uninitialized -D__HIP_PLATFORM_AMD__
# export CMAKE_CXX_FLAGS=-Wno-error=maybe-uninitialized -Wno-error=uninitialized -D__HIP_PLATFORM_AMD__
# See https://github.com/pytorch/FBGEMM/issues/2013 for more details about this regression

set -e

pushd $ROCM_WORKING_DIR > /dev/null
python3 -m venv .torch-build-venv
source .torch-build-venv/bin/activate
cd Torch
pip install -r requirements.txt
python tools/amd_build/build_amd.py
WITH_BLAS=FLAME ATEN_NO_TEST=ON BUILD_TEST=OFF USE_KINETO=OFF USE_NATIVE_ARCH=ON python setup.py bdist_wheel
pip install dist/*.whl
cd ../TorchAudio
USE_ROCM=ON HIP_PATH=$ROCM_INSTALL_DIR/lib:$ROCM_INSTALL_DIR python setup.py bdist_wheel
cd ../TorchVision
ROCM_HOME=$ROCM_INSTALL_DIR python setup.py bdist_wheel
deactivate

cd ..
mv -f Torch/dist/*.whl $ROCM_WORKING_DIR
mv -f TorchAudio/dist/*.whl $ROCM_WORKING_DIR
mv -f TorchVision/dist/*.whl $ROCM_WORKING_DIR
rm -rf .torch-build-venv $ROCM_WORKING_DIR/Torch/build $ROCM_WORKING_DIR/TorchAudio/build $ROCM_WORKING_DIR/TorchVision/build
popd > /dev/null
