FROM debian:12-slim

ARG ROCM_WORKING_DIR
ARG ROCM_INSTALL_DIR
ARG ROCM_GIT_CLONE_DIR=ROCm
ARG ROCM_GIT_TAG_VERSION=rocm-5.4.4
ARG DEBIAN_FRONTEND=noninteractive
ARG aptget_args="--no-install-recommends -y"

RUN apt-get update; \
    apt-get install $aptget_args build-essential gfortran cmake ninja-build ccache pkg-config \
                                 git \
                                 curl \
                                 kmod \
                                 python3-dev python3-venv python3-pip python3-yaml python-is-python3 \
                                 libnuma-dev \
                                 libelf-dev xxd \
                                 mesa-common-dev file \
                                 libmsgpack-cxx-dev \
                                 libfmt-dev \
                                 libsqlite3-dev libbz2-dev nlohmann-json3-dev \
                                 pybind11-dev libflame-dev \
                                 libblis-dev; \
    apt-get clean

RUN pip install --break-system-packages CppHeaderParser

RUN echo "$ROCM_INSTALL_DIR/lib\n$ROCM_INSTALL_DIR/lib/roctracer\n$ROCM_INSTALL_DIR/llvm/lib\n$ROCM_INSTALL_DIR/magma/lib" | tee /etc/ld.so.conf.d/rocm.conf
WORKDIR $ROCM_WORKING_DIR/$ROCM_GIT_CLONE_DIR
COPY rocm-core rocm-core

## ROCm sources

RUN curl -L https://github.com/ROCm/roctracer/raw/refs/tags/$ROCM_GIT_TAG_VERSION/inc/ext/prof_protocol.h -o $ROCM_WORKING_DIR/prof_protocol.h

# 1) LLVM
RUN git clone https://github.com/ROCm/llvm-project -b $ROCM_GIT_TAG_VERSION

# 2) HIPCC
RUN git clone https://github.com/ROCm/HIPCC -b $ROCM_GIT_TAG_VERSION

# 3) ROCm CMake modules
RUN git clone https://github.com/ROCm/rocm-cmake -b $ROCM_GIT_TAG_VERSION

# 4) ROCT Thunk Interface
RUN git clone https://github.com/ROCm/ROCT-Thunk-Interface -b $ROCM_GIT_TAG_VERSION

# 5) ROCm SMI Library
RUN git clone https://github.com/ROCm/rocm_smi_lib -b $ROCM_GIT_TAG_VERSION

# 6) ROCm Device Libraries
RUN git clone https://github.com/ROCm/ROCm-Device-Libs -b $ROCM_GIT_TAG_VERSION

# 7) Code Object Manager
RUN git clone https://github.com/ROCm/ROCm-CompilerSupport -b $ROCM_GIT_TAG_VERSION

# 8) HSA Runtime
RUN git clone https://github.com/ROCm/ROCR-Runtime -b $ROCM_GIT_TAG_VERSION

# 9) rocminfo
RUN git clone https://github.com/ROCm/rocminfo -b $ROCM_GIT_TAG_VERSION

# 10) half
RUN git clone https://github.com/ROCm/half -b $ROCM_GIT_TAG_VERSION

# 11) HIP
RUN git clone https://github.com/ROCm/ROCclr -b $ROCM_GIT_TAG_VERSION; \
    git clone https://github.com/ROCm/ROCm-OpenCL-Runtime -b $ROCM_GIT_TAG_VERSION; \
    git clone https://github.com/ROCm/HIP -b $ROCM_GIT_TAG_VERSION; \
    git clone https://github.com/ROCm/hipamd -b $ROCM_GIT_TAG_VERSION

# 12) HIPIFY
RUN git clone https://github.com/ROCm/HIPIFY -b $ROCM_GIT_TAG_VERSION

# 13) ROC-tracer
RUN git clone https://github.com/ROCm/roctracer -b $ROCM_GIT_TAG_VERSION

# 14) rocPRIM
RUN git clone https://github.com/ROCm/rocPRIM -b $ROCM_GIT_TAG_VERSION

# 15) rocRAND
RUN git clone --recursive https://github.com/ROCm/rocRAND -b $ROCM_GIT_TAG_VERSION

# 16) rocBLAS
RUN git clone https://github.com/ROCm/Tensile -b $ROCM_GIT_TAG_VERSION; \
    git clone https://github.com/ROCm/rocBLAS -b $ROCM_GIT_TAG_VERSION

# 17) rocSPARSE
RUN git clone https://github.com/ROCm/rocSPARSE -b $ROCM_GIT_TAG_VERSION

# 18) hipSPARSE
RUN git clone https://github.com/ROCm/hipSPARSE -b $ROCM_GIT_TAG_VERSION

# 19) rocSOLVER
RUN git clone https://github.com/ROCm/rocSOLVER -b $ROCM_GIT_TAG_VERSION

# 20) rocThrust
RUN git clone https://github.com/ROCm/rocThrust -b $ROCM_GIT_TAG_VERSION

# 21) hipBLAS
RUN git clone https://github.com/ROCm/hipBLAS -b $ROCM_GIT_TAG_VERSION

# 22) hipSOLVER
RUN git clone https://github.com/ROCm/hipSOLVER -b $ROCM_GIT_TAG_VERSION

# 23) hipCUB
RUN git clone https://github.com/ROCm/hipCUB -b $ROCM_GIT_TAG_VERSION

# 24) rocFFT
RUN git clone https://github.com/ROCm/rocFFT -b $ROCM_GIT_TAG_VERSION

# 25) hipFFT
RUN git clone https://github.com/ROCm/hipFFT -b $ROCM_GIT_TAG_VERSION

# 26) RCCL
RUN git clone https://github.com/ROCm/rccl -b $ROCM_GIT_TAG_VERSION

# 27) rocMLIR (no release tag for ROCm 5.4.4)
RUN git clone https://github.com/ROCm/rocMLIR -b rocm-5.4.3

# 28) MIOpen
RUN git clone https://github.com/ROCm/MIOpen -b $ROCM_GIT_TAG_VERSION

# 29) MIGraphX
RUN git clone https://github.com/ROCm/AMDMIGraphX -b $ROCM_GIT_TAG_VERSION

WORKDIR $ROCM_WORKING_DIR

## Third-party libraries

# 1) Protobuf 3.21.12
RUN git clone https://github.com/protocolbuffers/protobuf -b v3.21.12

# 2) Blaze 3.8.2
RUN git clone https://github.com/live-clones/blaze -b v3.8.2

# 3) MAGMA 2.6.2
RUN git clone https://github.com/icl-utk-edu/magma -b v2.6.2

# 4) Boost 1.79
RUN curl -L https://archives.boost.io/release/1.79.0/source/boost_1_79_0.tar.bz2 -o boost.tar.bz2

RUN tar -xf boost.tar.bz2; \
    rm boost.tar.bz2; \
    mv boost_1_79_0 boost

COPY script script
COPY patch patch
COPY build-rocm build-rocm
