#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/hipblas \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/lib/llvm/bin/amdclang++ \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DCMAKE_Fortran_FLAGS="-march=native -O3 -s -w" \
    -DAMDGPU_TARGETS="$AMDGPU_TARGETS" \
    -DBUILD_CLIENTS_TESTS=OFF \
    -DBUILD_CLIENTS_SAMPLES=OFF \
    -DBUILD_CLIENTS_BENCHMARKS=OFF \
    -G Ninja \
    $ROCM_SOURCE_DIR/hipBLAS

cmake --build $ROCM_BUILD_DIR/hipblas
cmake --install $ROCM_BUILD_DIR/hipblas --prefix $ROCM_INSTALL_DIR
