#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/rccl \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/lib/llvm/bin/amdclang++ \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DAMDGPU_TARGETS="$AMDGPU_TARGETS" \
    -DBUILD_TESTS=OFF \
    -G Ninja \
    $ROCM_SOURCE_DIR/rccl

cmake --build $ROCM_BUILD_DIR/rccl
cmake --install $ROCM_BUILD_DIR/rccl --prefix $ROCM_INSTALL_DIR
