#! /usr/bin/env bash

set -e

cd `dirname $0`
echo -e "\e[1m[1/5] Building ROCm 6.3 software stack...\e[0m"
docker-compose up --build rocm_build
echo -e "\e[1m[2/5] Commiting changes...\e[0m"
docker commit RDNA1_ROCm63_Build_Phase rdna1-rocm63:intermediate
echo -e "\e[1m[3/5] Building PyTorch and ONNX Runtime...\e[0m"
docker-compose up --build torchonnx_build
echo -e "\e[1m[4/5] Commiting changes...\e[0m"
docker commit RDNA1_ROCm63_TorchONNX_Build_Phase rdna1-rocm63:final
echo -e "\e[1m[5/5] Building the runtime image...\e[0m"
docker-compose up --build --detach runtime
