FROM rdna1-rocm63:final

ARG ROCM_WORKING_DIR
ARG ROCM_INSTALL_DIR

WORKDIR $ROCM_WORKING_DIR

RUN tar -cvf rocm.tar $ROCM_INSTALL_DIR; \
    tar -cvf torchonnx-wheels.tar *.whl

FROM ubuntu:24.04

ARG HOME_USER
ARG ROCM_WORKING_DIR
ARG ROCM_INSTALL_DIR
ARG DEBIAN_FRONTEND=noninteractive
ARG aptget_args="--no-install-recommends -y"

RUN apt-get update; \
    apt-get upgrade $aptget_args python3-dev python3-venv python3-tk \
                                 build-essential cmake \
                                 git \
                                 kmod \
                                 libnuma1 \
                                 libelf1t64 \
                                 libdrm-amdgpu1 \
                                 file libfile-which-perl liburi-encode-perl \
                                 libfmt9 \
                                 libflame1t64 libblis4 \
                                 pipewire-pulse pipewire-alsa ffmpeg libportaudio2 \
                                 weston libglu1-mesa; \
    apt-get clean

WORKDIR $ROCM_WORKING_DIR

COPY --from=0 $ROCM_WORKING_DIR/rocm.tar rocm.tar
RUN tar -xvf rocm.tar -C /; \
    rm rocm.tar

RUN echo "$ROCM_INSTALL_DIR/lib\n$ROCM_INSTALL_DIR/lib/roctracer\n$ROCM_INSTALL_DIR/lib/migraphx/lib\n$ROCM_INSTALL_DIR/lib/llvm/lib\n$ROCM_INSTALL_DIR/magma/lib" | tee /etc/ld.so.conf.d/rocm.conf; \
    ldconfig

RUN groupadd -r render; \
    useradd -mG audio,video,render -u 4999 $HOME_USER; \
    groupmod -g 49999 $HOME_USER

COPY --from=0 $ROCM_WORKING_DIR/torchonnx-wheels.tar /home/$HOME_USER/torchonnx-wheels.tar
RUN chown -R $HOME_USER:$HOME_USER /home/$HOME_USER
USER $HOME_USER

WORKDIR /home/$HOME_USER

RUN tar -xvf torchonnx-wheels.tar; \
    rm torchonnx-wheels.tar
