#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/hipcc \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=$ROCM_INSTALL_DIR/llvm/bin/clang \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/llvm/bin/clang++ \
    -DCMAKE_C_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DCMAKE_PREFIX_PATH="$ROCM_INSTALL_DIR" \
    -G Ninja \
    $ROCM_SOURCE_DIR/HIPCC

cmake --build $ROCM_BUILD_DIR/hipcc

mkdir -p $ROCM_INSTALL_DIR/hip/bin
cp $ROCM_BUILD_DIR/hipcc/hipcc.bin $ROCM_BUILD_DIR/hipcc/hipconfig.bin $ROCM_INSTALL_DIR/hip/bin
