#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/roct-thunk-interface \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=$ROCM_INSTALL_DIR/llvm/bin/clang \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/llvm/bin/clang++ \
    -DCMAKE_C_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DROCM_CCACHE_BUILD=ON \
    -G Ninja \
    $ROCM_SOURCE_DIR/ROCT-Thunk-Interface

cmake --build $ROCM_BUILD_DIR/roct-thunk-interface
cmake --install $ROCM_BUILD_DIR/roct-thunk-interface --prefix $ROCM_INSTALL_DIR
