#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/rocminfo \
    -DROCRTST_BLD_TYPE=Release \
    -DCMAKE_C_COMPILER=$ROCM_INSTALL_DIR/llvm/bin/clang \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/llvm/bin/clang++ \
    -DCMAKE_C_FLAGS="$COMPILER_FLAGS -Wno-error=unused-command-line-argument" \
    -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS -Wno-error=unused-command-line-argument" \
    -G Ninja \
    $ROCM_SOURCE_DIR/rocminfo

cmake --build $ROCM_BUILD_DIR/rocminfo
cmake --install $ROCM_BUILD_DIR/rocminfo --prefix $ROCM_INSTALL_DIR

pushd $ROCM_INSTALL_DIR/bin > /dev/null
mv -f rocm_agent_enumerator rocm_agent_enumerator.bak
echo -e '#!/usr/bin/sh\necho "gfx1010\\ngfx1012"' > rocm_agent_enumerator
chmod +x rocm_agent_enumerator
popd > /dev/null
