#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/hipify \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=$ROCM_INSTALL_DIR/llvm/bin/clang \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/llvm/bin/clang++ \
    -DCMAKE_C_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DCMAKE_INSTALL_PREFIX=$ROCM_BUILD_DIR/hipify/hipify \
    -DHIPIFY_CLANG_TESTS=OFF \
    -G Ninja \
    $ROCM_SOURCE_DIR/HIPIFY

cmake --build $ROCM_BUILD_DIR/hipify
cmake --install $ROCM_BUILD_DIR/hipify --prefix $ROCM_INSTALL_DIR

mkdir -p $ROCM_INSTALL_DIR/libexec/hipify
mkdir -p $ROCM_INSTALL_DIR/include/hipify/include
find $ROCM_BUILD_DIR/hipify/hipify -maxdepth 1 -type f -name "hip*" | xargs mv -t $ROCM_INSTALL_DIR/bin
find $ROCM_BUILD_DIR/hipify/hipify -maxdepth 1 -type f -name "find*" | xargs mv -t $ROCM_INSTALL_DIR/libexec/hipify
cp -r $ROCM_BUILD_DIR/hipify/hipify/include/* $ROCM_INSTALL_DIR/include/hipify/include
