#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/rocsparse \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/bin/hipcc \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DAMDGPU_TARGETS="$AMDGPU_TARGETS" \
    -DBUILD_CLIENTS_TESTS=OFF \
    -DBUILD_CLIENTS_SAMPLES=OFF \
    -DBUILD_CLIENTS_BENCHMARKS=OFF \
    -G Ninja \
    $ROCM_SOURCE_DIR/rocSPARSE

cmake --build $ROCM_BUILD_DIR/rocsparse
cmake --install $ROCM_BUILD_DIR/rocsparse --prefix $ROCM_INSTALL_DIR
