#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/hipsparse \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/bin/hipcc \
    -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS" \
    -DCMAKE_Fortran_FLAGS="$COMPILER_FLAGS" \
    -DAMDGPU_TARGETS="$AMDGPU_TARGETS" \
    -DBUILD_CLIENTS_TESTS=OFF \
    -DBUILD_CLIENTS_SAMPLES=OFF \
    -G Ninja \
    $ROCM_SOURCE_DIR/hipSPARSE

cmake --build $ROCM_BUILD_DIR/hipsparse
cmake --install $ROCM_BUILD_DIR/hipsparse --prefix $ROCM_INSTALL_DIR
