#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/rocfft \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=$ROCM_INSTALL_DIR/llvm/bin/clang \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/bin/hipcc \
    -DCMAKE_C_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DAMDGPU_TARGETS="$AMDGPU_TARGETS" \
    -DBUILD_CLIENTS_TESTS=OFF \
    -G Ninja \
    $ROCM_SOURCE_DIR/rocFFT

cmake --build $ROCM_BUILD_DIR/rocfft
cmake --install $ROCM_BUILD_DIR/rocfft --prefix $ROCM_INSTALL_DIR
