#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/hipfft \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/bin/hipcc \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument" \
    -DAMDGPU_TARGETS="$AMDGPU_TARGETS" \
    -DHIP_ROOT_DIR="$ROCM_INSTALL_DIR" \
    -DBUILD_CLIENTS_TESTS=OFF \
    -G Ninja \
    $ROCM_SOURCE_DIR/hipFFT

cmake --build $ROCM_BUILD_DIR/hipfft
cmake --install $ROCM_BUILD_DIR/hipfft --prefix $ROCM_INSTALL_DIR
