#! /usr/bin/env bash

set -e

pushd $ROCM_WORKING_DIR/boost > /dev/null
./bootstrap.sh
./b2 install cflags="$COMPILER_FLAGS -fPIC" cxxflags="$COMPILER_FLAGS -fPIC" link=static --prefix=$HOME/.boost --with-system --with-filesystem
popd > /dev/null
