#! /usr/bin/env bash

set -e

cmake \
    -B $ROCM_BUILD_DIR/migraphx \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=$ROCM_INSTALL_DIR/llvm/bin/clang \
    -DCMAKE_CXX_COMPILER=$ROCM_INSTALL_DIR/llvm/bin/clang++ \
    -DCMAKE_C_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument -L$HOME/.protobuf/lib -I$ROCM_INSTALL_DIR/include/rocblas" \
    -DCMAKE_CXX_FLAGS="-march=native -O3 -s -w -Wno-error=unused-command-line-argument -L$HOME/.protobuf/lib -I$ROCM_INSTALL_DIR/include/rocblas" \
    -DMIGRAPHX_ENABLE_MLIR=ON \
    -DGPU_TARGETS="$AMDGPU_TARGETS" \
    -DBUILD_TESTING=OFF \
    -DBLAZE_INCLUDE=$HOME/.blaze/include \
    -DProtobuf_LIBRARIES=$HOME/.protobuf/lib/libprotobuf.a \
    -DProtobuf_INCLUDE_DIR=$HOME/.protobuf/include \
    -DPROTOBUF_LIBRARY="protobuf" \
    -G Ninja \
    $ROCM_SOURCE_DIR/AMDMIGraphX

cmake --build $ROCM_BUILD_DIR/migraphx
cmake --install $ROCM_BUILD_DIR/migraphx --prefix $ROCM_INSTALL_DIR
